// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
    devtools: { enabled: true },
    content: {
        markdown: {
            tags: {
                a: "md-a",
                blockquote: "md-blockquote",
                code: "md-code",
                "code-block": "md-code-block",
                em: "md-em",
                h1: "md-h1",
                h2: "md-h2",
                h3: "md-h3",
                h4: "md-h4",
                h5: "md-h5",
                h6: "md-h6",
                hr: "md-hr",
                img: "md-img",
                label: "md-label",
                li: "md-li",
                ol: "md-ol",
                p: "md-p",
                strong: "md-strong",
                table: "md-table",
                tbody: "md-tbody",
                td: "md-td",
                th: "md-th",
                thead: "md-thead",
                tr: "md-tr",
                ul: "md-ul",
            },
        },
    },
    vue: {
        compilerOptions: {
            isCustomElement: (tag) =>
                [
                    "MdA",
                    "MdBlockquote",
                    "MdCode",
                    "MdEm",
                    "MdH1",
                    "MdH2",
                    "MdH3",
                    "MdH4",
                    "MdH5",
                    "MdH6",
                    "MdHr",
                    "MdImg",
                    "MdLabel",
                    "MdLi",
                    "MdOl",
                    "MdP",
                    "MdStrong",
                    "MdTable",
                    "MdTbody",
                    "MdTd",
                    "MdTh",
                    "MdThead",
                    "MdTr",
                    "MdUl",
                    "MdCodeBlock",
                ].includes(tag),
        },
    },
    components: {
        global: true,
        dirs: ["~/components", { path: "~/components/md", pathPrefix: "md" }],
    },
    modules: ["@nuxtjs/tailwindcss", "@nuxt/content", "@nuxt/image"],
});
