import MdA from "~/components/md/md-a.vue";
import MdBlockquote from "~/components/md/md-blockquote.vue";
import MdCode from "~/components/md/md-code.vue";
import MdCodeBlock from "~/components/md/md-code-block.vue";
import MdEm from "~/components/md/md-em.vue";
import MdH1 from "~/components/md/md-h1.vue";
import MdH2 from "~/components/md/md-h2.vue";
import MdH3 from "~/components/md/md-h3.vue";
import MdH4 from "~/components/md/md-h4.vue";
import MdH5 from "~/components/md/md-h5.vue";
import MdH6 from "~/components/md/md-h6.vue";
import MdHr from "~/components/md/md-hr.vue";
import MdImg from "~/components/md/md-img.vue";
import MdLabel from "~/components/md/md-label.vue";
import MdLi from "~/components/md/md-li.vue";
import MdOl from "~/components/md/md-ol.vue";
import MdP from "~/components/md/md-p.vue";
import MdStrong from "~/components/md/md-strong.vue";
import MdTable from "~/components/md/md-table.vue";
import MdTbody from "~/components/md/md-tbody.vue";
import MdTd from "~/components/md/md-td.vue";
import MdTh from "~/components/md/md-th.vue";
import MdThead from "~/components/md/md-thead.vue";
import MdTr from "~/components/md/md-tr.vue";
import MdUl from "~/components/md/md-ul.vue";
import { defineNuxtPlugin } from "#app";

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.component("MdA", MdA);
    nuxtApp.vueApp.component("MdBlockquote", MdBlockquote);
    nuxtApp.vueApp.component("MdCode", MdCode);
    nuxtApp.vueApp.component("MdCodeBlock", MdCodeBlock);
    nuxtApp.vueApp.component("MdEm", MdEm);
    nuxtApp.vueApp.component("MdH1", MdH1);
    nuxtApp.vueApp.component("MdH2", MdH2);
    nuxtApp.vueApp.component("MdH3", MdH3);
    nuxtApp.vueApp.component("MdH4", MdH4);
    nuxtApp.vueApp.component("MdH5", MdH5);
    nuxtApp.vueApp.component("MdH6", MdH6);
    nuxtApp.vueApp.component("MdHr", MdHr);
    nuxtApp.vueApp.component("MdImg", MdImg);
    nuxtApp.vueApp.component("MdLabel", MdLabel);
    nuxtApp.vueApp.component("MdLi", MdLi);
    nuxtApp.vueApp.component("MdOl", MdOl);
    nuxtApp.vueApp.component("MdP", MdP);
    nuxtApp.vueApp.component("MdStrong", MdStrong);
    nuxtApp.vueApp.component("MdTable", MdTable);
    nuxtApp.vueApp.component("MdTbody", MdTbody);
    nuxtApp.vueApp.component("MdTd", MdTd);
    nuxtApp.vueApp.component("MdTh", MdTh);
    nuxtApp.vueApp.component("MdThead", MdThead);
    nuxtApp.vueApp.component("MdTr", MdTr);
    nuxtApp.vueApp.component("MdUl", MdUl);
});
